# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess
import sys
from pytube import YouTube
import os
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def openFile(self):
        # path = "C:/Users"
        path = self.lineEdit_2.text()
        path = os.path.realpath(path)
        os.startfile(path)

    def save_path(self):
        if self.checkBox.isChecked():
            self.lineEdit_2.setReadOnly(True)
            #self.lineEdit_2.setText("C:\\Users\\jacqu\\Music")
        else:
            self.lineEdit_2.setReadOnly(False)

    def clear_text(self):
        self.lineEdit.clear

    def download(self):
        yt = YouTube(str(self.lineEdit.text()))
        video = yt.streams.filter(only_audio=True).first()
        destination = str(self.lineEdit_2.text()) or '.'
        out_file = video.download(output_path=destination)
        base, ext = os.path.splitext(out_file)
        new_file = base + '.mp3'
        os.rename(out_file, new_file)
        self.label_4.setText(yt.title + '.mp3' + " has been successfully downloaded.")
        self.label_4.setStyleSheet("color: green;")

    def __init__(self):
        self.statusbar = None
        self.menubar = None
        self.label_3 = None
        self.label_4 = None
        self.horizontalLayout_2 = None
        self.pushButton = None
        self.pushButton_2 = None
        self.pushButton_3 = None
        self.horizontalLayout = None
        self.lineEdit_2 = None
        self.lineEdit = None
        self.verticalLayout = None
        self.label_2 = None
        self.label = None
        self.verticalLayout_3 = None
        self.verticalLayout_2 = None
        self.centralwidget = None
        self.checkBox = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 364)
        MainWindow.setStyleSheet("QWidget{\n"
                                 "    color: #fff;\n"
                                 "background: #121212;\n"
                                 "}\n"
                                 "QLineEdit{\n"
                                 "background-color:#111111;\n"
                                 "color: #666;\n"
                                 "border: 1px solid #333;\n"
                                 "  background-color: #121212;\n"
                                 "padding-bottom: 25px;\n"
                                 "}\n"
                                 "QLineEdit:focus{\n"
                                 "    border: 1px solid #fff;\n"
                                 "    color: #fff;\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "background-color: #666;\n"
                                 "color: #fff;\n"
                                 "padding: 10px 40px;\n"
                                 "border-radius: 5px;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "background-color: #777;\n"
                                 "}\n"
                                 "QPushButton:pressed{\n"
                                 "background-color: #888;\n"
                                 "}\n"
                                 "QLabel{\n"
                                 "    color:white;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
                                         "\n"
                                         "QDialogButtonBox {\n"
                                         "    background-color:#666;\n"
                                         "    border: none;\n"
                                         "}\n"
                                         "\n"
                                         "QDialogButtonBox:hover {\n"
                                         "    background-color: #666;\n"
                                         "}\n"
                                         "\n"
                                         "QDialogButtonBox:pressed {\n"
                                         "    background-color: #888;\n"
                                         "}\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("LEMON MILK Bold")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        font.setBold(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        font.setBold(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_3.clicked.connect(self.download)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3.clicked.connect(self.clear_text)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton.clicked.connect(self.openFile)

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.checkBox.stateChanged.connect(self.save_path)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: #fff;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouPy - Youtube Downloader"))
        self.label.setText(_translate("MainWindow", "Youtube Downloader"))
        self.label_2.setText(_translate("MainWindow", "by Jacques Katsuva"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Copy the link here"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Copy the path of your folder"))
        self.pushButton_3.setText(_translate("MainWindow", "Download"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.pushButton.setText(_translate("MainWindow", "Open File"))
        self.checkBox.setText(_translate("MainWindow", "Save emplacement"))
        self.label_4.setText(_translate("MainWindow", "No file downloaded"))
        self.label_3.setText(_translate("MainWindow", "v1.0"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
